import Head from 'next/head'
import PromptForm from '@/components/PromptForm'
import { Container, Box } from '@chakra-ui/react';
import { useState } from 'react';
import TableResult from '@/components/TableResult'
import { Word } from '@/types';
import { Configuration, OpenAIApi } from "openai";
export default function Home() {
  const [results, setResults] = useState<Word[]>([]);
  const [isOpen, setIsOpen] = useState(false);
  const [loading, setLoading] = useState(false);

  async function extarctWords(article: string) {
    setLoading(true);
    setIsOpen(true);
    const configuration = new Configuration({
      apiKey: process.env.NEXT_PUBLIC_OPENAI_API_KEY,
    });
    const openai = new OpenAIApi(configuration);
    try {
      const completion = await openai.createChatCompletion({
        model: "gpt-3.5-turbo",
        messages: [{ role: "assistant", content: `You are a useful word assistant, you will help me extract 10 IELTS English words from this article, and give the Chinese translation . Your returned content should be in a JSON format such as :[{"w":,"m":},{"w":,"m":}].The article is ${article}` }],
      });
      const parseContent = JSON.parse(completion.data.choices[0].message?.content);
      setResults(parseContent)
    } catch (error) {
      console.error(error);
    }
  }
  return (
    <>
      <Head>
        <title>WordGPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box height="100vh" paddingTop={130}>
        <Container maxW='3xl' centerContent>
          <PromptForm extractWords={extarctWords} />
          <TableResult results={results} />
        </Container>
      </Box>

    </>
  )
}
